### ISSUE TITLE
Join together COVID Time Series data with Mobility data

### ISSUE THREAD

**Issue by aksomers** [amitp06/COVID-19#1]
Need to join the two datasets. A few things (at least) to resolve before doing so.

- [x] One dataset uses the word "County" and "Parish" at the end of each county, have to trim words or find a FIPs mapping. 
- [x] There's likely to be other county spelling issues as well that we'll run into.
- [x] One dataset has each date as a column, the other has it as rows. Need to resolve this for the merge.
- [x] Format of dates is different between datasets, need to parse this.
- [x] Assuming these are the main things, then join on State/County/Date.

**Comment by aksomers** [comment]
Made progress on 1 and 3 in the data_merge.R code.

**Comment by amitp06** [comment]
Regarding #2: I decided to join on FIPS instead of State/County since it was available in both and caused less joining issues.

#4 and #5 are complete in the latest commit.

There is some data loss due to time period and some differences in counties included. More sanity checks would help, but my initial impression is that it looks acceptable. (See comments in data_merge.R)

**Comment by aksomers** [comment]
For now, I think it's acceptable. I think we can push on and circle back later.
